# Generated by Django 4.0.1 on 2022-02-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='back_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='back_id_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='front_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='front_id_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_kyc_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='Kiprotich', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
