# Generated by Django 4.0.1 on 2022-02-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_status',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Bad', 'Bad'), ('Defaulter', 'Defaulter')], default='Good', max_length=40),
        ),
    ]
